---
# tasks file for proxy

- name: Install danted
  apt:
    pkg:
      - dante-server
    state: present
    update_cache: true
- name: Copy config file
  template:
    src: danted.conf.j2
    dest: /etc/danted.conf
    mode: '0644'
  notify: Restart danted
# TODO possibility password direct with vault
- name: Create proxy socks users
  user:
    name: '{{ item.name }}'
    password: '{{ item.passhash }}'
    state: present
    shell: /bin/false
    groups: users
    system: true
  loop: '{{ proxy_socks_users }}'

- name: Get public IP
  shell: |
    set -o pipefail
    ip a show {{ proxy_socks_public_interface }} | egrep '^ *inet ' | awk '{printf substr($2, 1, length($2)-3)}'
  register: public_ip
  changed_when: false
- name: Copy script ssh-redirect
  template:
    src: iptables-ssh.sh.j2
    dest: '{{ proxy_socks_ssh_script }}'
    mode: '0755'
  notify: Apply ssh iptables rules
- name: Copy service file ssh-redirect
  template:
    src: iptables-ssh-redirect.service.j2
    dest: /etc/systemd/system/ssh-redirect.service
    mode: '0644'
  notify: Apply ssh iptables rules

- name: Allow port in UFW {{ proxy_socks_port }}
  ufw:
    rule: allow
    port: '{{ proxy_socks_port }}'
  when: proxy_socks_ufw
