---
# handlers file for proxy
- name: Apply ssh iptables rules
  systemd:
    name: ssh-redirect.service
    state: restarted
    daemon_reload: true
    enabled: true
  retries: 2
  delay: 3
  register: result
  until: result is not failed

- name: Restart danted
  systemd:
    name: danted
    state: restarted
    enabled: true
